// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Outty.Api.Data;

#nullable disable

namespace Outty.Api.Migrations
{
    [DbContext(typeof(OuttyDbContext))]
    partial class OuttyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Outty.Api.Data.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Outty.Api.Data.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("Outty.Api.Data.ExperienceLevel", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("ExperienceLevel1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ExperienceLevel");

                    b.HasKey("Id")
                        .HasName("PK__Experien__3214EC07E67C48FF");

                    b.ToTable("ExperienceLevel", (string)null);
                });

            modelBuilder.Entity("Outty.Api.Data.Goal", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Goals__3214EC0716AD728E");

                    b.HasIndex(new[] { "Name" }, "UQ__Goals__737584F6C732F116")
                        .IsUnique();

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Outty.Api.Data.Interest", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Interest__3214EC0788383DD8");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Outty.Api.Data.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "SentAtUtc");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Outty.Api.Data.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreferredDistance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Profiles__3214EC079C6C5579");

                    b.HasIndex("State");

                    b.HasIndex(new[] { "UserId" }, "UQ__Profiles__1788CC4DB6141892")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Outty.Api.Data.ProfileInterest", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<byte>("InterestId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ExperienceLevelId")
                        .HasColumnType("tinyint");

                    b.HasKey("ProfileId", "InterestId");

                    b.HasIndex("ExperienceLevelId");

                    b.HasIndex("InterestId");

                    b.ToTable("ProfileInterests");
                });

            modelBuilder.Entity("Outty.Api.Data.ProfilePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__ProfileP__3214EC0767F6CF95");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilePhotos");
                });

            modelBuilder.Entity("Outty.Api.Data.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__States__3214EC07AE9BB063");

                    b.HasIndex(new[] { "Name" }, "UQ__States__737584F65996DB36")
                        .IsUnique();

                    b.HasIndex(new[] { "Abbreviation" }, "UQ__States__9C41170EE396952E")
                        .IsUnique();

                    b.ToTable("States");
                });

            modelBuilder.Entity("Outty.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC071A36E780");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105347ABCBCCC")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProfileGoal", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<byte>("GoalId")
                        .HasColumnType("tinyint");

                    b.HasKey("ProfileId", "GoalId")
                        .HasName("PK__ProfileG__21A8771919449138");

                    b.HasIndex("GoalId");

                    b.ToTable("ProfileGoals", (string)null);
                });

            modelBuilder.Entity("Outty.Api.Data.ConversationParticipant", b =>
                {
                    b.HasOne("Outty.Api.Data.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Outty.Api.Data.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Outty.Api.Data.Message", b =>
                {
                    b.HasOne("Outty.Api.Data.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Outty.Api.Data.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Outty.Api.Data.Profile", b =>
                {
                    b.HasOne("Outty.Api.Data.State", "StateNavigation")
                        .WithMany("Profiles")
                        .HasForeignKey("State")
                        .HasPrincipalKey("Abbreviation")
                        .IsRequired()
                        .HasConstraintName("FK__Profiles__State__7A672E12");

                    b.HasOne("Outty.Api.Data.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Outty.Api.Data.Profile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Profiles__UserId__797309D9");

                    b.Navigation("StateNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Outty.Api.Data.ProfileInterest", b =>
                {
                    b.HasOne("Outty.Api.Data.ExperienceLevel", "ExperienceLevel")
                        .WithMany("ProfileInterests")
                        .HasForeignKey("ExperienceLevelId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileIn__Exper__08B54D69");

                    b.HasOne("Outty.Api.Data.Interest", "Interest")
                        .WithMany("ProfileInterests")
                        .HasForeignKey("InterestId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileIn__Inter__07C12930");

                    b.HasOne("Outty.Api.Data.Profile", "Profile")
                        .WithMany("ProfileInterests")
                        .HasForeignKey("ProfileId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileIn__Profi__06CD04F7");

                    b.Navigation("ExperienceLevel");

                    b.Navigation("Interest");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Outty.Api.Data.ProfilePhoto", b =>
                {
                    b.HasOne("Outty.Api.Data.Profile", "Profile")
                        .WithMany("ProfilePhotos")
                        .HasForeignKey("ProfileId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfilePh__Profi__7F2BE32F");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileGoal", b =>
                {
                    b.HasOne("Outty.Api.Data.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileGo__GoalI__0F624AF8");

                    b.HasOne("Outty.Api.Data.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileGo__Profi__0E6E26BF");
                });

            modelBuilder.Entity("Outty.Api.Data.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Outty.Api.Data.ExperienceLevel", b =>
                {
                    b.Navigation("ProfileInterests");
                });

            modelBuilder.Entity("Outty.Api.Data.Interest", b =>
                {
                    b.Navigation("ProfileInterests");
                });

            modelBuilder.Entity("Outty.Api.Data.Profile", b =>
                {
                    b.Navigation("ProfileInterests");

                    b.Navigation("ProfilePhotos");
                });

            modelBuilder.Entity("Outty.Api.Data.State", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Outty.Api.Data.User", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Profile");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
